import { z } from 'zod';

export const fieldSchema = z.object({
  id: z.string(),
  name: z.string(),
  acreage: z.number(),
  lat: z.number().nullable().optional(),
  lng: z.number().nullable().optional(),
  fsaFarmNumber: z.string().optional(),
  fsaTractNumber: z.string().optional(),
  fsaFieldNumber: z.string().optional(),
  producerShare: z.number().optional(),
  irrigationPractice: z.string().optional(),
  intendedUse: z.string().optional(),
  boundary: z.any().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
  notes: z.string().optional(),
}).strict();

const binSchema = z.object({
  id: z.string(),
  name: z.string(),
  capacity: z.number(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const plantRecordSchema = z.object({
  id: z.string(),
  fieldId: z.string(),
  fieldName: z.string().optional(),
  seedVariety: z.string().optional(),
  acreage: z.number(),
  crop: z.string().optional(),
  plantDate: z.string().optional(),
  fsaFarmNumber: z.string().optional(),
  fsaTractNumber: z.string().optional(),
  fsaFieldNumber: z.string().optional(),
  intendedUse: z.string().optional(),
  producerShare: z.number().optional(),
  irrigationPractice: z.string().optional(),
  seasonYear: z.number(),
  timestamp: z.number().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

export const sprayRecordSchema = z.object({
  id: z.string(),
  fieldId: z.string(),
  fieldName: z.string().optional(),
  products: z.array(z.any()).optional(),
  windSpeed: z.number().optional(),
  temperature: z.number().optional(),
  sprayDate: z.string().optional(),
  startTime: z.string().optional(),
  endTime: z.string().optional(),
  equipmentId: z.string().optional(),
  applicatorName: z.string().optional(),
  licenseNumber: z.string().optional(),
  epaRegNumber: z.string().optional(),
  seasonYear: z.number(),
  timestamp: z.number().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
  targetPest: z.string().optional(),
  windDirection: z.string().optional(),
  relativeHumidity: z.number().optional(),
  treatedAreaSize: z.number().optional(),
  treatedAreaUnit: z.string().optional(),
  totalAmountApplied: z.number().optional(),
  involvedTechnicians: z.string().optional(),
  mixtureRate: z.string().optional(),
  totalMixtureVolume: z.string().optional(),
  siteAddress: z.string().optional(),
  cropOrSiteTreated: z.string().optional(),
  applicationMethod: z.string().optional(),
  rei: z.string().optional(),
  notes: z.string().optional(),
  complianceProfile: z.string().optional(),
  isPremixed: z.boolean().optional(),
  nonCompliant: z.boolean().optional(),
  nozzleType: z.string().optional(),
  nozzleSize: z.string().optional(),
  pressurePsi: z.number().optional(),
  boomHeight: z.number().optional(),
  actualSpeed: z.number().optional(),
  windSpeedEnd: z.number().optional(),
  windDirectionEnd: z.string().optional(),
  tempEnd: z.number().optional(),
  sensitiveAreaCheck: z.boolean().optional(),
  sensitiveAreaNotes: z.string().optional(),
}).strict();

const harvestRecordSchema = z.object({
  id: z.string(),
  fieldId: z.string(),
  fieldName: z.string().optional(),
  destination: z.string().optional(),
  binId: z.string().optional(),
  bushels: z.number(),
  moisturePercent: z.number().optional(),
  landlordSplitPercent: z.number().optional(),
  harvestDate: z.string().optional(),
  fsaFarmNumber: z.string().optional(),
  fsaTractNumber: z.string().optional(),
  seasonYear: z.number(),
  timestamp: z.number().optional(),
  crop: z.string().optional(),
  landlordName: z.string().optional(),
  scaleTicketNumber: z.string().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const hayHarvestRecordSchema = z.object({
  id: z.string(),
  fieldId: z.string(),
  fieldName: z.string().optional(),
  date: z.string().optional(),
  baleCount: z.number(),
  cuttingNumber: z.number().optional(),
  baleType: z.string().optional(),
  temperature: z.number().optional(),
  conditions: z.string().optional(),
  seasonYear: z.number(),
  timestamp: z.number().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const grainMovementSchema = z.object({
  id: z.string(),
  farm_id: z.string(),
  binId: z.string(),
  binName: z.string().optional(),
  type: z.string().optional(),
  bushels: z.number(),
  moisturePercent: z.number().optional(),
  sourceFieldName: z.string().optional(),
  destination: z.string().optional(),
  price: z.number().optional(),
  seasonYear: z.number(),
  timestamp: z.number().optional(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const savedSeedSchema = z.object({
  id: z.string(),
  name: z.string(),
  crop: z.string().optional(),
  variety: z.string().optional(),
  supplier: z.string().optional(),
  lotNumber: z.string().optional(),
  year: z.number().optional(),
  notes: z.string().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const fertilizerRecipeSchema = z.object({
  id: z.string(),
  name: z.string(),
  npkRatio: z.string().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const sprayRecipeSchema = z.object({
  id: z.string(),
  name: z.string(),
  products: z.array(z.any()).optional(),
  applicatorName: z.string().optional(),
  licenseNumber: z.string().optional(),
  targetPest: z.string().optional(),
  epaRegNumber: z.string().optional(),
  farm_id: z.string(),
  deleted_at: z.string().nullable().optional(),
}).strict();

const fertilizerApplicationSchema = z.object({
  id: z.string(),
  farm_id: z.string(),
  fieldId: z.string(),
  fieldName: z.string().optional(),
  date: z.string().optional(),
  acres: z.number(),
  fertilizer_formula: z.string().optional(),
  timestamp: z.number().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  deleted_at: z.string().nullable().optional(),
  seasonYear: z.number(),
}).strict();

const tillageRecordSchema = z.object({
  id: z.string(),
  farm_id: z.string(),
  fieldId: z.string(),
  fieldName: z.string().optional(),
  date: z.string().optional(),
  implementType: z.string().optional(),
  notes: z.string().optional(),
  seasonYear: z.number(),
  timestamp: z.number().optional(),
  deleted_at: z.string().nullable().optional(),
}).strict();

export const backupSchema = z.object({
  fields: z.array(fieldSchema).optional(),
  bins: z.array(binSchema).optional(),
  plantRecords: z.array(plantRecordSchema).optional(),
  sprayRecords: z.array(sprayRecordSchema).optional(),
  harvestRecords: z.array(harvestRecordSchema).optional(),
  hayHarvestRecords: z.array(hayHarvestRecordSchema).optional(),
  fertilizerApplications: z.array(fertilizerApplicationSchema).optional(),
  tillageRecords: z.array(tillageRecordSchema).optional(),
  grainMovements: z.array(grainMovementSchema).optional(),
  savedSeeds: z.array(savedSeedSchema).optional(),
  fertilizerRecipes: z.array(fertilizerRecipeSchema).optional(),
  sprayRecipes: z.array(sprayRecipeSchema).optional(),
  activeSeason: z.number().optional(),
  rolloverDate: z.string().optional(),
}).strict();

export type BackupData = z.infer<typeof backupSchema>;