import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Capacitor } from '@capacitor/core';
import { native } from '@/lib/native';

interface ExportPdfOptions {
  title: string;
  subtitle: string;
  headers: string[];
  rows: (string | number)[][];
  fileName: string;
  summaryText?: string;
  summaryValue?: string;
  footerText?: string[];
  orientation?: 'portrait' | 'landscape';
  tableCellPadding?: number;
  tableFontSize?: number;
}

export function exportToPdf({
  title,
  subtitle,
  headers,
  rows,
  fileName,
  summaryText,
  summaryValue,
  footerText,
  orientation = 'portrait',
  tableCellPadding = 3,
  tableFontSize = 8
}: ExportPdfOptions) {
  const doc = new jsPDF({ orientation });

  // Add Title
  doc.setFontSize(18);
  doc.setTextColor(40);
  doc.text(title.toUpperCase(), 14, 22);

  // Add Subtitle
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(subtitle, 14, 30);

  // Add Table
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 35,
    styles: {
      fontSize: tableFontSize,
      cellPadding: tableCellPadding,
    },
    headStyles: {
      fillColor: [45, 90, 27], // bg-primary equivalent (#2D5A1B)
      textColor: 255,
      halign: 'left',
    },
    columnStyles: {
      // Right align numeric columns if they contain only numbers or %
      ...headers.reduce((acc, header, index) => {
        const isNumeric = ['ACRES', 'BUSHELS', 'MOIST %', 'LL %', 'SHARE %', 'TOTAL', 'BALE COUNT', 'YOUR SHARE', 'SPLIT %', 'TOTAL BU.'].includes(header.toUpperCase());
        if (isNumeric) {
          acc[index] = { halign: 'right' };
        }
        return acc;
      }, {} as any)
    },
    didDrawPage: (data) => {
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      const str = `Page ${data.pageNumber}`;
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      doc.text(str, data.settings.margin.left, pageHeight - 10);
      doc.text('Generated by AcreLedger', pageSize.width - 50, pageHeight - 10);
    }
  });

  // Add Summary if provided
  let finalY = ((doc as any).lastAutoTable?.finalY || 35) + 10;
  if (summaryText && summaryValue) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40);
    doc.text(summaryText.toUpperCase(), 14, finalY);
    
    doc.setTextColor(45, 90, 27); // text-primary equivalent
    const valueWidth = doc.getTextWidth(summaryValue);
    const pageWidth = doc.internal.pageSize.width;
    doc.text(summaryValue, pageWidth - valueWidth - 14, finalY);
    finalY += 10;
  }

  if (footerText?.length) {
    const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.width;
    // Right margin mirrors the left (14) so text never runs off the page.
    const maxWidth = pageWidth - 28;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(40);
    // `splitTextToSize` wraps each source line to the page width; each wrapped
    // line becomes its own entry so long footers (e.g. activity timelines)
    // paginate correctly instead of overflowing the right edge.
    const wrappedLines = footerText.flatMap(line => doc.splitTextToSize(line, maxWidth));
    if (finalY + wrappedLines.length * 6 > pageHeight - 20) {
      doc.addPage();
      finalY = 20;
    }
    wrappedLines.forEach((line) => {
      if (finalY + 6 > pageHeight - 20) {
        doc.addPage();
        finalY = 20;
      }
      doc.text(line, 14, finalY);
      finalY += 6;
    });
  }

  if (Capacitor.isNativePlatform()) {
    native.sharePdf(fileName, doc);
  } else {
    doc.save(fileName);
  }
}
