import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ExportPdfOptions {
  title: string;
  subtitle: string;
  headers: string[];
  rows: (string | number)[][];
  fileName: string;
  summaryText?: string;
  summaryValue?: string;
}

export function exportToPdf({
  title,
  subtitle,
  headers,
  rows,
  fileName,
  summaryText,
  summaryValue
}: ExportPdfOptions) {
  const doc = new jsPDF();

  // Add Title
  doc.setFontSize(18);
  doc.setTextColor(40);
  doc.text(title.toUpperCase(), 14, 22);

  // Add Subtitle
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(subtitle, 14, 30);

  // Add Table
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 35,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [45, 90, 27], // bg-primary equivalent (#2D5A1B)
      textColor: 255,
      halign: 'left',
    },
    columnStyles: {
      // Right align numeric columns if they contain only numbers or %
      ...headers.reduce((acc, header, index) => {
        const isNumeric = ['ACRES', 'BUSHELS', 'MOIST %', 'LL %', 'SHARE %', 'TOTAL', 'BALE COUNT', 'YOUR SHARE', 'SPLIT %', 'TOTAL BU.'].includes(header.toUpperCase());
        if (isNumeric) {
          acc[index] = { halign: 'right' };
        }
        return acc;
      }, {} as any)
    },
    didDrawPage: (data) => {
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      const str = `Page ${data.pageNumber}`;
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      doc.text(str, data.settings.margin.left, pageHeight - 10);
      doc.text('Generated by AcreLedger', pageSize.width - 50, pageHeight - 10);
    }
  });

  // Add Summary if provided
  if (summaryText && summaryValue) {
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40);
    doc.text(summaryText.toUpperCase(), 14, finalY);
    
    doc.setTextColor(45, 90, 27); // text-primary equivalent
    const valueWidth = doc.getTextWidth(summaryValue);
    const pageWidth = doc.internal.pageSize.width;
    doc.text(summaryValue, pageWidth - valueWidth - 14, finalY);
  }

  doc.save(fileName);
}
