import { beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { createJsPdfMock } from '@/test/jspdfMock';

const pdf = createJsPdfMock();
vi.doMock('jspdf', () => ({ default: pdf.JsPdf }));
vi.doMock('jspdf-autotable', () => ({ default: pdf.autoTable }));
vi.doMock('@capacitor/core', () => ({ Capacitor: { isNativePlatform: () => false } }));
vi.doMock('@/lib/native', () => ({ native: { sharePdf: pdf.sharePdf } }));

let exportToPdf: typeof import('../pdfExport').exportToPdf;
beforeAll(async () => {
  ({ exportToPdf } = await import('../pdfExport'));
});

const baseOptions = {
  title: 'Landlord Summary',
  subtitle: 'Test Farm — Crop Year 2026 — Landlord: John Smith',
  headers: ['FIELD', 'ACRES', 'BUSHELS'],
  rows: [
    ['North 80', 80, 12000],
    ['South 40', 40, 6000],
  ],
  fileName: 'landlord-summary.pdf',
};

describe('exportToPdf', () => {
  beforeEach(() => pdf.reset());

  it('renders an uppercased title and the farm-name subtitle verbatim', () => {
    exportToPdf(baseOptions);

    const text = pdf.allText();
    expect(text).toContain('LANDLORD SUMMARY');
    expect(text).toContain('Test Farm — Crop Year 2026 — Landlord: John Smith');
  });

  it('passes headers and rows to the table and draws the page footer', () => {
    exportToPdf(baseOptions);

    const tables = pdf.autoTables();
    expect(tables).toHaveLength(1);
    expect(tables[0].head[0]).toEqual(['FIELD', 'ACRES', 'BUSHELS']);
    expect(tables[0].body).toHaveLength(2);

    // didDrawPage footer (invoked once by the harness).
    const text = pdf.allText();
    expect(text).toContain('Page 1');
    expect(text).toContain('Generated by AcreLedger');
  });

  it('renders an uppercased summary label with its value', () => {
    exportToPdf({ ...baseOptions, summaryText: 'Total Bushels', summaryValue: '18,000' });

    const text = pdf.allText();
    expect(text).toContain('TOTAL BUSHELS');
    expect(text).toContain('18,000');
  });

  it('wraps long footer lines via splitTextToSize so they paginate instead of overflowing', () => {
    // Deterministic wrapper: every 10-char chunk becomes its own line.
    pdf.setSplitTextBehavior((text) => text.match(/.{1,10}/g) ?? [text]);

    exportToPdf({
      ...baseOptions,
      footerText: ['A very long activity timeline line that must wrap'],
    });

    const text = pdf.allText();
    expect(text).toContain('A very lon');
    expect(text).toContain('g activity');
    // The un-wrapped source line must never be drawn whole.
    expect(text).not.toContain('A very long activity timeline line that must wrap');
  });

  it('adds pages when the footer does not fit on the first page', () => {
    const footerText = Array.from({ length: 50 }, (_, i) => `Timeline entry ${i + 1}`);

    exportToPdf({ ...baseOptions, footerText });

    expect(pdf.addPageCount()).toBeGreaterThanOrEqual(1);
    const text = pdf.allText();
    expect(text).toContain('Timeline entry 1');
    expect(text).toContain('Timeline entry 50');
  });

  it('saves the document with the requested filename on the web path', () => {
    exportToPdf(baseOptions);

    expect(pdf.savedAs()).toEqual(['landlord-summary.pdf']);
    expect(pdf.sharePdf).not.toHaveBeenCalled();
  });
});
