/* 
  AcreLedger Precision Ag — Service Worker
  Version: 2.1.0
*/

import { precacheAndRoute } from 'workbox-precaching';

// Force the new service worker to take over immediately
self.addEventListener('install', () => {
  self.skipWaiting();
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
