/* 
  AcreLedger Precision Ag — Service Worker
  Version: 2.1.2
*/

import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

// Force the new service worker to take over immediately
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation requests (like /settings, /activity) by serving index.html
// This prevents 404 errors on page refresh for client-side routes.
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);
